name: sevdesk_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.3
  go_router: ^11.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flex_color_scheme: ^7.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.1.1
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
